### ISSUE TITLE
Accepting an offer should merge data to a contract

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#295]
As a contractor,
the application should merge my data into the correct contract after I accept the offer.

Some related tasks:

- [x] Download unmerged document from S3 & store temporarily (estimated in #308)
- [x] Get all data into map %{project: %{...}, offer: %{...}, ...} (estimated in #291)
- [x] Run script on data (estimated in #309)
- [x] Upload new contract to 4hrs
- [x] Add merged document URL to documents table (add column offer_id) 2hrs

**Comment by jonscottfilm** [comment]
Number 1 task :)

**Comment by JMurphyWeb** [comment]
Remaining tasks in this issue amount to 1 day

**Comment by JMurphyWeb** [comment]
Small bits to do:
- [ ] Add integration tests 
- [ ] Test flow locally
- [ ] Test flow on Heroku
- [ ] Limit document type dropdown to just paye and sched d, ensure they are both being saved exactly the same as in offer.contract_type (should probably add restrictions into our changesets)
- [ ] Use existing file name (not 'test.pdf') in merger function
- [ ] Ensure files are being saved somewhere sensible
- [ ] Ensure files are being deleted after merge is done

**Comment by JMurphyWeb** [comment]
Heroku error writing file:

 ```
could not write to file "/app6e119aaab40543b3948798f74591670b-fillable.pdf": read-only file system
```

**Comment by JMurphyWeb** [comment]
https://stackoverflow.com/questions/12416738/how-to-use-herokus-ephemeral-filesystem

save them to /tmp

**Comment by JMurphyWeb** [comment]
@jonscottfilm as you know this is now testable 🎉

**Comment by jonscottfilm** [comment]
Get in!! Well done guys.

Closing.
