### ISSUE TITLE
Document Security S3

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#376]
We need to implement measures for making our documents more secure in S3. At the moment, anyone with the url of a document stored in S3 will be able to view and/or download it. 

- [ ] implement a solution for restricting access to our S3 files

**Comment by jackcarlisle** [comment]
Good stack overflow question
https://serverfault.com/questions/506763/storing-and-serving-files-securely-for-multiple-clients

**Comment by jackcarlisle** [comment]
Blog Post on AWS S3 Security:
https://cloudacademy.com/blog/amazon-s3-security-master-bucket-polices-acls/

**Comment by jackcarlisle** [comment]
Restricting access with AWS Cloudfront:
http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html

**Comment by jackcarlisle** [comment]
## Task list for serving private content

- [ ] Require your users to access your content only through CloudFront. The method that you use depends on whether you're using Amazon S3 or custom origins:
*Amazon S3* - http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html

- [ ] Specify the AWS accounts that you want to use to create signed URLs or signed cookies - http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-trusted-signers.html

- [ ] Write your application to respond to requests from authorized users either with signed URLs or with Set-Cookie headers that set signed cookies - http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-choosing-signed-urls-cookies.html

**Comment by jonscottfilm** [comment]
I know you know this, but just to stress that **security of the data is paramount.**
The product will be dropped if we had a data breach.

Without creating too much work for us for MVP, remember we do have my friends security firm who can PEN test.

cc: @beccacca

**Comment by JMurphyWeb** [comment]
@jonscottfilm we hear you. This and encrypting our pdfs #400  are our key security concerns.
