### ISSUE TITLE
Docusign task list

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#380]
From spike issue #330 

Some points to consider:
- We probably want to always have access to the 'raw'/unsigned merged contract 
  - Need to store the signed/partly signed documents separately in the documents table
- We need to add multiple signees for each document
  - New table called signees
- We need to keep track of who has signed a document 
  - New table linking signees with documents called signatures

________________________

### Tables

**documents**:
- add `envelope_id` column that allows us to retrieve documents from docusign
- possibly add `status` column that indicates if the document is `original`/`merged`/`signed` allowing us to easily distinguish (not strictly necessary but is a bit more declarative & clear)
- alternatively could look into splitting the documents table into a original_documents table and a signed/merged_table so we can have `merged_url` and `signed_url` for each document on each offer in one row

**signees**
- columns: `signee_email`, `signee_role`, `signee_name`, `document_id`
  - again this will lead us to storing lots the first 3 columns many times for each document so may make sense to relate the signees to a project
  - @jonscottfilm will all documents in a specific project need to be signed by the same people?

**signatures**
- columns: `signee_id`, `document_id`, `signee_order`, `signed?`
  - `signee_order` will store where they should be in the approval chain 
  - @jonscottfilm is this necessary?
  - `signed?` => `true` - that signee has signed, `null` - not yet signed, `false` - rejected contract

_______________________

### User flow

After SIGN button is pushed by contractor, we can get all signees attached to that document (or project depending on Jono's feedback) and list them with checkboxes next to their name and role:
eg:
- [ ] You (Cashier)
- [ ] Fran Swift (Producer)
- [ ] Simon Marr (Director)
- [ ] Kat Stevens (Company CEO)

These will get checked off when the signee has done their thing.  Once all are signed, we will download and store the signed document on S3 and replace the merged document and checkboxes with a downloadable signed copy. If someone rejects, the flow will stop and a new offer will have to be made.

_____________________

### Keeping our DB up to date

Longer term I think Webhooks are the way to go, I have not investigated this nor have I looked into alternatives. For now we can either:
- Periodically call the Docusign api on all our un-finished merged contracts
- Make the call every time a contractor/PM looks at the offer if the document is not fully signed

@jonscottfilm please take a look at this proposed implementation and give feedback.

**Comment by jonscottfilm** [comment]
I've replied within the issue, seemed easier. (although spent more time formatting, ha!) 
Tell me if you'd prefer I don't do that. :)

**Comment by jonscottfilm** [comment]
Crap. and now I just lost it all.
