### ISSUE TITLE
FINAL fixes before going live (good luck @Murphy!)

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#524]
**Description |  Who/When** 
---
**Remaining tasks**

**Essential**
- [x] 1. Have app emails come from onboard@teamengine.co.uk, Team Engine domain email account. @jonscott trying to add G Suite to Squarespace.

- [x] 2. Discussed with @jackcarlisle : MVP solution for 'Update project documents' #499 - ADD warnings before a PM sends an offer, and contract accepts or rejects an offer:
REMOVE PM WARNING - _Changed our minds. It's unneccessary_: ('Ensure all details are correct before proceeding, e.g. email address and contract type?')
**EDIT Contractor** accept: 'Proceed if all details are accurate and documents correct?'
Contractor reject: 'Speak with the project to amend an offer. A rejected offer cannot be reversed'
- [x] 2.1 - De-Karma #544 (find & replace, IF sure that won't break anything) - I know of 2 places: In Log In screen 'New to Karma' change to 'New to engine' (lowercase). Flash success message in Create account screen, says: 'A verification email has been sent to jonscottfilm+28@gmail.com. Click the link in the email to gain full access to Karma.' Change to engine (lowercase).
- [x] 3. In HTML emails, change ALL button links to point to relevant teamengine pages, not Heroku pages. **Only 1 of these seems to be in, and one error link. ALL need to be teamengine links**
- [x] 4. Terms link in email footers: change to: https://app.teamengine.co.uk/terms (the not-logged-in version, with hidden startpack & log out links)
- [x] 5. Privacy link in email footers: change to: https://app.teamengine.co.uk/privacy (the not-logged-in version, with hidden startpack & log out links)
- [x] 6. In 'offer response' email, make 'accepted' and 'rejected' offer_status, **bold**. Colours are too light to read as they currently are. _Could_ make colours _slightly_ darker if bold doesn't crack it.
- [x] 7. In HTML emails, remove the word 'Image' in all embedded images, and ideally the 'this is a link, 'hand icon' when hovered over, IF there is not link there. Think this only means removing links from the header logo's, the footer logo should stay as link to website, but remove word 'Image'.
- [x] 8. contact link in email footer: build subject line: 'enquiry from user_fullname (or user_email)
- [x] 9. contact link in email footer: fix body text, by inserting new lines between content (enquiry and contacts)
- [x] 10. Team engine logo in email footers: change link to point to: https://www.teamengine.co.uk
- [x] 11. Team engine logo in the email footers, is not horizontally centrally aligned, when email wraps.
- [x] 11.1 remove 'Daily or Weekly' from docusign filename
- [x] 12. add favicon to all app webpage tabs (Jono will create Sun 16 Jul)
- [x] 13. enlarge ALL checkboxes to match radio button circle diameter

**Nice-to-have**
- [x] 14. make daily/weekly titlecase in offer details views
- [x] 15. Agent email field in startpack should fail on submission if not correct email format (all lowercase, @, .domain extension)
- [x] 16. Labels of uploaded documents in start pack - 'Box Rental' change to 'Box inventory', 'Equipment Rental' change to 'Equipment inventory'
- [x] 17. When user updates own firstname or surname in edit profile, write over value in database so fullname  updates in 'edit offer' form
- [x] 18. remove word 'image' from upload filenames in offer details
- [x] 19. Privacy policy: change 'Introduction, Section 1 and Section 2' headers to Title-case (from Upper-case), and change colour from black to HEX#525252

**Docusign essentials**
- [x] | 17. Change Docusign account to Team Engine account, and get new API keys
- [x] | 18. add ability embed 'date signed' in docusign envelope API.
- [x] | docusign emails - replace email body blurb with same content as subject:  'Project_codename' - agreement: User_first_name User_last_name, Offer_job_title (Offer_department) (ADD 2 blank lines prior, for separation)
- [x] | remove start date from docusign filename

**To backlog**
- [x] | Offer response' HTML email - _still_ screwy when zoom in/enlarge, certainly in Gmail. Looks like header image width not scaling  #down.
- [x] | Under document in project view - show actual approval chain to make it easy to see what has been set up and what hasn't

---
**Functional Essentials**
- [x] | Edit offer view - if there are already figures in fee per day, box rental, box cap, equipment rental, equipment cap and vehicle allowance  formatting is wrong - over £1000 goes to 1.e3 and under £1000 only has 1 decimal place
- [x] | **BUG** vehicle logic still not working - insists on everything (including documents) without vehicle allowance or own vehicle check box ticked
- [x] | **BUG** vehicle tick box is preventing partial startpack from saving - deletes all new entries when it errors (#528)
- [x] | **BUG** now Loan out vs PAYE logic is working, is there no need for default loan out ticked (preferable if possible @jackcarlisle)?
- [x] | **BUG** profile update - didn’t work at all (not for first or last name!) (#526)
- [x] | Fee per day in offer needs to be able to enter to 2 decimal places not an integer (construction deals are xx.xx per day!)
- [x] | change Engine logo&title image from SVG to JPG100 login/create account/forgot password screen. Issue happening is font for 'engine' in logo, is not Lato in some browsers. System font over-ride? (JPG100 is in the same HTML files folder - I'll Slack you the Drive link)
- [x] | Change engine.onboard emails to come from onboard@teamengine.co.uk

---
**Essential rewrites of HTML email notification subjects, as such:**

Email type | **subject contents** 
(include single speechmarks around 'project codename', and spaces between e n g i n e)
- [x] | create account | **e n g i n e - create account to join 'Project_codename'**

- [x] | verify email | **e n g i n e - verify your email**
- [x] | new offer | **e n g i n e - invitation to join 'Project_codename'**
- [x] | revised offer | **e n g i n e - revised offer from 'Project_codename'**
- [x] | reset password | **e n g i n e - reset your password**
- [x] | accept offer | **e n g i n e - you have joined 'Project_codename'**
-  | rejected offer | **e n g i n e - offer rejected: 'Project_codename'**
*(currently we don't email the contractor when they have rejected an offer because they don't need to take any further action regarding that offer)*
- [x] | offer response | **e n g i n e - User_first_name User_last_name has offer_status your offer**

---
**Ideally get done**
- [x] | Forgotten password - uses old logo
- [x] | forgotten password link - change to forgot/reset password
- [x] | image at top of body of emails has a download tag. (Change SVG to JPG100, which is in the same HTML files folder)
- [x] | profile update - 'Edit user' should be in sub header
- [x] | profile update - breadcrumbs needed
- [x] | forgotten password link - add to edit profile view too
- [x] | What is the order of offer tiles in project view and dashboard view.  Seems to be date order - needs reversing so newest update at top.
- [x] | Resize add button

---
**Nice-to-haves**
- [x] | In project details and offer views, FINAL formatting tweaks:
- [x] | add units after # days per week, i.e. 5 'days' - currently says nothing.
- [x] | days per week, show no decimal place, unless present in choice, i.e. 5, 5.5, 6
- [x]  | ALL CAPS on the currency choice, currently it is 'gbp', 'usd', 'eur', should be GBP, USD, EUR

------
Done:
- [x] 3. align field values (first name, last name, email) in edit profile view, into 2 distinct columns, in line with rest of startpack
- [x] 4. remove placeholders in first name last name in create account screen
- [x] 5. Project_codename should be used in all places by default. Change page views which use project_name, to Project_codename.
- [x] **#506** - Suss subdomain address for the app:
URL to appear as: app.teamengine.co.uk - application (on Heroku)
URL to appear as: www.teamengine.co.uk - website (on Squarespace)
- [x] 1. Simplify PAYE/Student Loan UX in Startpack view (main contractor UX):
_Insert vertical space between fields:_
‘Radio button: I have another job or receive a state or occupational pension’
**and**
‘Check the box if you have a student loan which is not fully repaid’

_Insert one line vertical space AND horizontal divider line (same colour as sub-section header line), between fields:_ 
Last Student Loan question 'Radio button: No’
**and**
‘Upload a file of your Schedule D letter’
(effectively grouping PAYE questions in one group, and Sched-D and Loan Out in another group)

_Insert one line vertical space AND horizontal divider line (same colour as sub-section header line), between fields:_
Upload a file of your loan out company certificate
Accepted file types: pdf, jpeg, png
Choose file
**and**
Bank name

_Move VAT number to between fields:_
Upload a file of your Schedule D letter
Accepted file types: pdf, jpeg, png
Choose file
**and**
Check the box if you deal through a loan out company

- [x] 1.1. PAYE+Equipment=Schedule-D logic, seems to be working incorrectly for _all_ PAYE job titles, even though 'provision of equipment' is empty. e.g. VFX On Set PA = PAYE, but an offer with Equipment, should not make that contract Sched-D. Correct logic is: PAYE+Equipment in offer+'provision of equipment' in job title list=Schedule-D.
- [x] | Insert link to the website (www.teamengine.co.uk) in the footer of the app.
- [x] | Vehicle Logic - now with Vehicle unchecked, and/or no allowance, Vehicle Allowance document (if present) ALWAYS merges.- [x] | In main header, edit 'engine' wording to be same size as startpack & log out wording. f3, p12, fw5 (Font 3, position from logo 12 (from 13), Font weight 5)
 IF not bigger... currently engine gets lost. 
- [x] | Log in / Create account screens, Terms of use page should have logo and engine, BUT with NO home link, to identify application to which the terms refer. Keep startpack and log out labels/links hidden.
- [x] | Terms of use link in create account (and in emails) needs to link to a free access version where you don't have to be logged in to read it. | - | discuss JC/JS
- [x] | Privacy link in emails needs to link to a free access version | - | discuss JC/JS
- [x] | Add "shoot start date" label in project tile on dashboard | - | JC
- [x] | Add "shoot" to start date label in project tile on project view | - | JC
- [x] | Add space between title and code name in project tile on project view (see how it appears on dashboard) | - | JC
- [x] | Project details view - when no document uploaded to the section the banner still reads: you have no deals/forms/info instead of Contracts/Forms/Information | - | JC
- [x] | Edit offer view and edit project view -page title not in grey subheader bar | - | JC
- [x] | revised offer email - should be Dear "first name of crew member" currently picking up project manager | - | JC
- [x] | Create account - change "I have read and accept the terms and conditions" to "I have read and accept the terms of use" | - | JC - lower priority
- [x] | Project details view - add project docs - change category names to plurals - contracts/forms | - | JC - lower priority
- [x] | Edit offer view - back breadcrumb misaligned and is it right breadcrumb | - | JC - lower priority
- [x] | emails - all uses of code name should have single 'quotation marks' around - whether in body or subject | - | JC - lower priority
- [x] | emails - codename to be in bold in body | - | JC - lower priority
- [x] | throughout engine - where codename shown in quotation marks should be single | - | JC - lower priority
- [x] | Accepted offer email - lose capital A on accepted in body of email | - | JC -very low priority
- [x] | Accepted offer email - accepted in green | - | JC -very low priority
- [x] | Accepted offer email - rejected in red | - | JC -very low priority
- [x] | more info needed banner in edit startpack from offer view - needs rewording | - | JS/BW
- [x] | Dashboard breadcrumb on dashoard view - lose it as it doesn't take you anywhere? | - | not essential
- [x] | lose the word document under each merged document - ie Merged start form NOT merged start form document | - | not essential

**Comment by JMurphyWeb** [comment]
```
 tabs: %{dateSignedTabs: [%{documentId: 70,
                  tabLabel: "date_signed_1\\*"}],
               signHereTabs: [%{documentId: 70,
                  tabLabel: "signature_1\\*"}]}
```

Not creating a datesigned tab..

**Comment by JMurphyWeb** [comment]
inline checkbox class:
```
    height: 2rem;
    display: inline-block;
    transform: translateY(28%);
    width: 3rem;
```

**Comment by JMurphyWeb** [comment]
More breathing space: 

<img width="541" alt="screen shot 2017-07-17 at 09 40 10" src="https://user-images.githubusercontent.com/12638261/28260649-f765a8fa-6ad3-11e7-906b-245163a20613.png">

**Comment by JMurphyWeb** [comment]
@jonscottfilm i totally get the desire/need to have an issue like this.  Thing is it messes with our workflow a bit and makes it difficult for future devs to pick their way through history if they need to. In the future can we group similar small fixes together into different issues?

Eg. email copy issue
Small ui fixes
Copy changes
...

Thanks!

**Comment by jonscottfilm** [comment]
Agreed. Understood.

**Comment by jonscottfilm** [comment]
Massive closure.
