### ISSUE TITLE
*COSMETICS LIST

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#592]
## **Minor cosmetic, but necessary 😉, adjustments:**
(a more palatable list, linking to existing issues)

- [ ] 1. **HTML email formatting** #580 priority 3 (6 sub-issues)

- [ ] 2.  **Fix button borders** priority-4 #578 

- [ ] 3.  **Fix main header (all views) border colour** priority-4 #576 

- [ ] 4. **Fix format of Studio/Production company label** priority 5 #591
Lowecase the c of company
